#!/usr/bin/env python
# generate characteristic grids from start_id to end_id
# id range from 1 to 60
# usage: generateCM start_id end_id

import os
import sys

advectProjectPath = "/home/jingcoz/workspace/clion_projects/advect"
bunnyFileExePath = "cmake-build-default/bunnyFile"
config = "config"
log = "log"

if len(sys.argv) != 3:
    print "[usage] generateCM start_id end_id"
    exit(0)

start_id = int(sys.argv[1])
end_id = int(sys.argv[2])

exePath = os.path.join(advectProjectPath, bunnyFileExePath)
cfgPath = os.path.join(advectProjectPath, config)
logName = "generateCM-{start}-{end}.log".format(start=start_id, end=end_id)
logPath = os.path.join(advectProjectPath, log, logName)

for id in xrange(start_id, end_id + 1):
    command = "{exe} {cfg} -as {id} | tee {log}".format(exe=exePath, cfg=cfgPath, id=id, log=logPath)
    os.system(command)
